/************************************************************\
 **  Copyright (c) 2011-2022 Anlogic, Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/Administrator/Desktop/16_ov2640_sdram/al_ip/32Divider.v
 ** Date	:	2022 10 30
 ** TD version	:	5.6.59063
\************************************************************/

/*************************************************************************
* 作者：吴文强
* 日期：2019/08/12
* 说明：串行移位除法器
**************************************************************************/

module 32Divider 
#(
	parameter W_NUM = 32, // 分子位宽
	parameter W_DEN = 32, // 分母位宽
    parameter S_NUM = "UNSIGNED", // "UNSIGNED"
    parameter S_DEN = "UNSIGNED"  // "UNSIGNED"
)
(
	input	wire                clk,
	input	wire                rst,
	
	// 除法器输入
	input	wire [W_NUM-1:0]    numerator,
	input	wire [W_DEN-1:0]    denominator,
	input	wire			    start,
	
	// 除法器输出
	output	wire [W_NUM-1:0]    quotient,
	output	wire [W_DEN-1:0]    remainder,
	output	reg                 done
);
`pragma protect begin_protected
`pragma protect version = 1
`pragma protect encrypt_agent = "Anlogic"
`pragma protect encrypt_agent_info = "Anlogic Encryption Tool anlogic_2019"
`pragma protect key_keyowner = "Anlogic", key_keyname = "anlogic-rsa-006"
`pragma protect key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 128)
`pragma protect key_block
S/nNZBUFyIoL2oL9+G7vpKAD7n7pFdSmig3R69e0XofqtzPWKfFAV3Z5/KWZxiXN
AJQGR9QOigvpyTQGJ5agjClkX1DYuOARRdWQ8X4cb+nZqoev8siqTli891qofvjc
iXBkzXmOAg2kdcO2IvRksrcMlrSWC0XwldgBZF6f5Uc=
`pragma protect key_keyowner = "Cadence Design Systems.", key_keyname = "CDS_RSA_KEY_VER_1"
`pragma protect key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 256)
`pragma protect key_block
LWgKbzB+bLDHFKmcRkik922xcV/RGSGBkwZbiHaykgUwkqcrBfewJQnPCCn1Wbre
RHNBtFe2hdndu3/lD2Zblp5nyNriyYg7aI+RNByTChCViBsmhJvM0p8mlzn+V44T
Bn0TRpTNDxTBmEbqShRTZNKXr28Ww/Jh52U2vF+ATcbuST7W3NUTfHIckTGpkab4
KfwwCtKAYY9FNVJXe4XqMycqcU9R1LrN+4byMfjHKnTxa3C7FVwg82/WKjWA0zEf
if2MhGKF4jf24uG+Qai9tZ2nQgDMl6iSY72UyyO/ToewD96nDol4kMaHhZ1eqEAx
wpTlqbRcbvLahhdSRAzMUg==
`pragma protect key_keyowner = "Mentor Graphics Corporation", key_keyname = "MGC-VERIF-SIM-RSA-1"
`pragma protect key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 128)
`pragma protect key_block
LnBpV3einjMlT7zvCR5zK/Wx0MYXOkNZ5ZkICEsNTwjgwYwk3P3YsVkNbHGlQWCY
GgXtHz7mG67ASp9IA1VB3hU/nsYH5xeakRtX41ZrDlf64JvZdxL8piD77+2Z7ofs
Gv/tYa7N52al0fqvvgNcShl1QP+sYwtLER54xHiWq24=
`pragma protect key_keyowner = "Mentor Graphics Corporation", key_keyname = "MGC-VERIF-SIM-RSA-2"
`pragma protect key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 256)
`pragma protect key_block
dKf5yW5C1SzxnAf0T//PyiTEvMv5oyhHftLryqEAv9t3Nx7byWw3/pHe/mL6BsCY
1XjKD/3Z2PUSK2ZSRaOgAOvedubASlr6zU/BytaVlXQhNmS4A9GwPF9H8+Oi5rsQ
GqgsLrrfzbJeHJXX4I7R+POaAn9U6aFaGgFLL9bKIM6P8Ei7OekEqyB3jVbDeVKs
W6WoHx8MUoL239D+23i72QXjlq5ehmhVv7XYyl8aOb9cmiJ3gMWLMbqsRsf+6eLM
+KtM7Ut23YniFe0y8rDOJNj7UBfkkpViHJMKr4P/VEVqjqXamLqybiHqji0HHxvL
n9gB5EnGOMaHRyCn2kHEUA==
`pragma protect key_keyowner = "Synopsys", key_keyname = "SNPS-VCS-RSA-2"
`pragma protect key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 128)
`pragma protect key_block
QoUlsVV4SCSdEvnw8CmTyF4rr3dcEquswUDfYKSd0JHQ+1AxC1wKlKUyToHPnG1m
KlWtn9Tk6uZeykCZr//wVOdOBOvDCVEQNBR0ubKqAguhVDrSgYRSKuNtODCJJgmD
Gq1ydyNQm3HyZqO/7kLrZniUFPIuRBTWS6pdEmJZOTE=
`pragma protect data_method = "AES128-CBC"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 4912)
`pragma protect data_block
NU9XSGlJbHhoc1dZU1ZSeE3sSw4i5FYK2skwUDuzZ9UXeGGZS3uFQ/wTGKPdmA2B
adyMvJruql8J1cWbwBDPavQ91Vbn+AYQy6zPuM0tITXJJjEFftL1Pn2jyliKrgM6
lmFwN7sAsDfHY86KIySlcOsZ9dUeEC0A8556OQnUtxUcmJHpIf4w15lz4TNIk8vh
WH+Zf8v8RUtqT/gd4QkOHz9PgzrmD9jpDZT/OTkWmo+sM67EpRXmYOKeHoA66p83
7k6/bZNCTcoWePBd1TXSxm5J8A4Ephxaw3y7nkYkQxoqL2kJfBrjuSlldKsys9HD
1CV8zhJ3yiSwVb14cM+RSDDs8FrIAnArTYdEEPwj8WXKO2W3mQnZrsPP+uV/uiE1
MORtUuo4v9YdR01t6axJ3h6T/HvA2JDUzffycKaAEXUvyEHsWsKWlvyrMRFefvjn
WbGVbUUI4/QNW6Shjl0VnyO4iedPPO5Sfgowb+bxMuTEM87W+fvJ0RgIPU92FnkM
XntYJ/s87+94XWkcHbKMFnNJjb4LQsTvYZOpyTitbSKOFHrXGIIW31geH2SPbUBc
qGlnG5B8ZXg1RhXYpmYvCX9JrMLDe7tuF+oX+tUuoPhy83+IzqHd+7iXvt1K+eWK
vVyvpm4Pv2BA7RVSUjoKL4SV6jLa9jDEEHHNuISF9QSuBk0ZZ0hCQehe3BgExGAU
7z9kRfnaAQY+Nhlgj2LMkxKuFPqTxbmKZQr0+NSwcqpvNTFzYpHG9iLpb6GJGbUZ
Ru4ddWnf8pmAO9FMlmUR0aCeuUowJB3rwqk0zCMPC2V+qQlA3lcec975GJ8D81cy
1eUHXgb9f4BeqfBOEWUbeXPFYZ0m4CflAx19by7pO5GTBegsMuNZlODoYHsfKBCc
KPZUK5bCZek/PdF1Lp2YLpaUtCoqCkjhuA8LhNepB1AH6Oyzp7RBXlDcTC+hsmrC
UpHL/2SzuNllCfptZjlX/xXCVEJ72AiLlSWOj6kVQ6H3YJsoCDZL9qecCGAwO1nf
jy3tTUHglm5G1ZjttjMeWebRzw3ciox9UcN60y7q5Ro/k72RxAyBhR9lm2xjvZWN
uC1+TwYNIoKKIOvPoTWEFpt6h/qEX5xJPeapNxFxRBvsZLWYgEpsl8WIVc2kvUEz
GCwvxicaAZ4N2z4LyQBLcC2j9RtK4QVxtsx1OGFTJ6tcnsdgPUOcur5Pi4G1Z06e
KCh/pOZfWudYHXUoXafBxZRl95Z9FVvt5FoJVN27TAjev/Nhq9yEnPFFHRXTn3wk
3qvyfzwTdzcMIL/A76remPorc5fAK8rAuJmwf+0yaXLuUsP42F+B+02kmKSqofnz
9oieYG54W+UPGHAIrBZtFfy1G2U79EHDLg7uRbXRAnSE8LzFlAPQoULmgXHqGRaP
pfdsEBCCzxxjE9rqXXM9FgMYLZqxWSs40qpYVOQjE9Maj+5uMi28Ad8uERvvxgGF
dwqam22bsvKBs/lYULM4IslPIM8RxvwloYgl7W7Xyv2+zzdlx4nCUD859zgXyT2e
SPw+Q2lGo43WgKcfN+HVMX+C1nQBeUI9vF62cGKQsTJBdZ1NHqUrObJUpR+OSUQR
N5pblaVw/NU6GmJLS0cW+4T5ozDMpwXU3SNqbwUmBiIXw9eoOULJRuwtWzElFQyy
QjgTNDV9SBW04Bu79ted3kfTAueI/OW1+xKN3ifm2lMFjJGTF12vIBimGv8NZpIg
sQrAQfnpgw4l4uB6nWXbFbVrcDv5xwDhBq7iyR2RLGUzdPWQWa3zGA1vTeqg1Ko/
KxoDfITWTJx4ahyo6ZF7bWvx3sXhij+TJ3AWj1olAEweEOI0wZ7y9tGTAh9wezeT
Jd2I0+zHkFKG8U1n6MnTRSecpttZixTy0LyP7bIHZuumeBfT4IYjjvRUWd+F8sY6
Av1wPuykHCqL86UougU7PV/G6gwt3rD/0MscHPCZdtjFoj1EcAGckOxfkAFDEQTv
v6wJ8asxIFnThr9LchTywOS+Yd0sk57ErZmj6XzgMxRShOSpAt+LPQeGFrZoxDLp
sybnSRojJdhIJaBBfwtRpvad7jdIt+l9SL4hyN/glQSjHbogqz6/u20je0aHEiZx
Gk5unPltUl46SbtJGiOrzY7+B+BIG+5/+JFJKm287b+l3Gn+nL5lIS+Dc8R4mFGY
WR9jqujhYUx6JuNn9p1W6vaUzhQ/iRa2xr9YL4rBwBXtguH8/IP+QYVWk8eE8/Y0
5ks+cka/Y1KVYHhWpspel0ZUnj0BswgoWTeTWQuN/qj3WVYNBbGxk6v9D8PJCmmK
8eDBfpOFsCYNA3TDLqkTwqAdbgS9m0xQZxjahvfAlKOJDFWDVcAOngdXyj6QrEpd
j9mxvovVrZOwwAImgaIzlDzSGjMOXTlEkoeP87nf+v7oMaXc3Ku/aW3Gv0WwsvOE
1YPHviZPwdASWnCYqmP6LcYHMCWJhFjExdJVVx+eRYtaq4OMAaGyTFvqJltZzeGO
+dUTT6MYw8tG27l4Al7T7/Q21qz/ogX5hXVf7nqUIAIWkBufMlcBi7h7vIxcnaH7
KLuBmmpvHYciAZb9bOoHjbdZzuTTjO8qLqW1tVDd3evYfrlveDYeIXP+qS7HUkqj
6PBa9Cd8KbkEHpOreR4GkqNyqbWwMgo1RVER5k2AsHJ7oAUnW75wjKWgbNPVN1nZ
/RW10sNSQ8J5PEXPO+4QLy4Zxn+Kzu8cRfNd+3Vu0NJoduoQKR/nJdPxOq6svPbb
aeWc4RL7T2x4YaxGgqbv7HBaIHb0AQD3VGSIRNAdvRINWVEgWymIHHxSKrut2Kvd
A1KFLMMANasoA3KEXl/bXHF6WcdWuyh2coDv5xr/wgtiFm6pP66nOA/2cYKxi2w3
+61HwHknTr0IROSh31ScUw5QkJ3EdLjg2gIxCv0pSNY7qEHXtcAoBTty0+qydRGB
nOMC94BhBNeSVcUSONyLjeW9RxtBWVeiqy7WKRWNtSwllSWfkbd/015KJakJHbkP
fdbjJuFnnKKHKQvfvpjyUcrqE/xgXuLcCPtiTbcw2GZLjOeSuqSenR5LXbDcEUzN
u37y4o4+j9H1v1PpAiHytUhTCaoXzhf/+fhbXcL7SGPXcLSuDA8wff6rCdRHf3AU
KubOW319phetGfwjfRixXP2YVJj61aChF4yhYcBKFQL94CrfDQptpWYbFyXTjICT
nhMEeJAPd50Ut4LMzBpewio7DI5PHCJreiPL8760Xn1taBkV8drfzcgG5wW/lKgq
DkSYGNP4Li2oXMdXhlfasH6GbZvv66j9ZlowKbqjMJECH/Qd/diaWz8sP6NCg34w
kOoHO4oK8E241fuB7gZVq+Kdnd4ZAD8prSx4s3qepz2c6Ql+43o3LY+Nntgbz+fd
p4/CklwkWq1WGl03zWxOkh+RIRWiFWbOUdR/QWc1+5T5g/6tjVSWlokd/PwaP3Xr
T/eB1f7GVZvnMMioqG0MzyNEC97QGslb4KCk1D5HlW0GYPnEts+a9nvi2wRrZIJI
L0gqLg8xGbY8L0dszGMnKeHDKjTcVgDrqUBVDeHq71wrFvpHJJIABhAJ+r1+eEeJ
shrQI306yw1rLqY2IfkpVHnplg1aEytPTvwNdu0T480ZfE/6roVbYJgfX25tP3oE
5GTZm5qHpzixughX+VbRyr7P58dr3hh1MgqxQUDmXP3gHquF4tTuDKuZj2bW6fIe
aNzpvi05ppOJmNO6l7agHkAETE4sxzZUswh5tfBjmVm2HhyBMfJqihJyHtmjMRPc
jqikZ9+osWeYdLbbcuhcR5bj/RA+r5rJwmZco5vK1ksJscgTlI8xyLa7CEyLZbtW
xqHgcqxPcBfu60eKniJn2GDW5Vahz3ffNfFLFTKgaP++spHa5twNIfb1MjWFm5pO
r4NTsWAcD8rXG9G7Qe6k7JuHDMLrFx1lAGpHh5iUMvieP8WurRWDTizJ2+S40M2e
9SrjR/Wo+eO6ILQyuR5dHdZtGG2R6t4angrGZXJELYUfyNTlhYn1Fc5Yy+5YJW7c
rj3DWLAeynpug4Y8omCaBtVJW2Y0mV0OolgQOfCNqIZ8Pa4+Ix3zvkwIGlA2qsR8
kDN6Yzkm6qfO3mfNnR6M/yY+qYMmtAsb7qL58baT+qyP25/Vdjz7xqZFQvADHiGI
HZ5WbvevlLX1WAWeW6ZWW4DTmMxTzSEEwCImCJa2XpqGu13vOHxRFJkL9LHppo+G
q/YKLJtlPHE3oSflKYZLR8LB4Yt2q3ZyheAxqMnL3DcKWNW2yRjCXrbhENboSqRT
lmfxzvUunSgLvxheEF2orqZpgMKahldYJ2DJwp/BmXIVpSxEps6HxXYV4judKb6Y
j8TlNO10IgJtU+xy+qtYLQM6rcI1Nj6AOK7Tzh2I3a8GncjybzsDwYMFtTxuWvD6
7BWQDKE6vIxIPK3lt4Q472Kcb0mkMdFYFJHnkxpkFMTI5KdmRumUHHEQxuNYufSb
bt2YwmiwHBRAdSqUDqiMDCNUikUZ2tXFBSQu71u3G27+iskw+VEumjKH60d+DlhN
zch1kLcdLoVRAYtcL6TD1BUlsKlXKkapoMNT3HsQ4MfqbL5SHmESZz92B5biaGL0
J1TOfMDk3shUSjsfPkdb00BRRItzG+SeSWKZqwG//hvfhcdEQCJZ0Dds9MsMyT4K
tY2FOhBJ00MbAL1iqkwcYPKAKWgqnQeQPpWjv/F8HB50IpqXEtp35mO//QpWebHA
rGJkEwZFXmFLmxRq2VYfNgVcESrFHhkB5SxmkKDjZ0MRidn7XhooAhoTCcGffMJB
075nBJ5k7qjrmTcypt253KuIsF+vbETJuEjWWi5ibIxUpq4+N8HDw1XE/TCFQGxD
VHUjrUJKJKMWg1Kq0Dvp7oDav/dx7hCTHbvS99T5C8e623ptPxYjq2Q9nBpyAFza
uMvGd5sKzfDdrmsgSrNmJ1mnHjhUZ6J2pVFbIKPAn647ZRCcYXPWr9+q7faQdwNx
tPxZ+jjCydzSs3T6F3tjeGv6hcjzPlaNh0WELmnreOC3hYw0mKdRH3c+21B7ZKQV
Q+paG+BZgD396ZkyAcM9f2n7VDqf39eHpxd/Y1/rZhldmh9wf4MQdzWo5jfZb0fa
aC3Lm79IVy1PTMhb5VVoIIs+WOp80Zr8fukvPfnnqiK2mF/vMak80h1FnwRtlVpL
ltLpqn/ILtXFtiZkLRO/85+4/uROG8yZVIKj5+nFvph3dXAnDHVS3KxUHnf9WHl/
wasiQKb7GQFbS6f55Y/IXM1N2yb6zNnPSvCpm7au0eZKxjd2meAE3aQVyRTd8fnd
hx5D6iItP9+0niEscH87q0yxCM29UzTm7+jCcu68M4BSkUYajDcEkjd+tpi3D2JA
XLf784niUeIrVUtW8KF13rkUnqPeS4U898n2H4tyiZrrcK0GVEKUmbUNFZovuyKz
QSeB7tdPYh9uDxK/jAEHouAPbis2uqNuReq++e2Q22HrsGg83Qz/c5+0swc9tkSA
aAlyGgPBJnr9zlw4UQFEGH01lIQ9kr9B3vNUB0TbqrdLEhGZBZtnhCR0fzlB0xsH
BnADenZXvYLVTvdv9OZK+gpN0Pc5oI0BaqCrksOv45VIfTAkx0sr+EoGBloImEa9
JFjr5g4exXquEuaovt8LujmkP4XcZfDxqkXWpQz4H9Ski+MjOdZJRozJnjCXIgOh
V9tuukVjhfE8a0pxA+bwog8g8bS87WE5/n+41xFw3b9Ss0x7ipQdPKCP7XahuEtt
x6r086cOH6VnmwPtWzFfTP5j9WrLNl/e710ScJE8olhxOyH6F3AltYM1lBOk+XKw
m6M5ohPolEARziwH94Ezsc6agxyChrddBhzvgUXczPWKrkTVUi9iCesD5Fof11sG
gOf+4kViG7L+6k+P8hUJ57BFwAwaNzrbHYUQ1oJZG0pneWCk444fWcYOgwWPoPWE
T9pztzCLLDp7GSusVVWahY5KPRupcuHvbbTm4ReKKBEXGFO8HxpBn9gU6Kj2nhWk
oCEj4qjHpH6pp7At477pV4I0uTSahdViaW6O6m7JwA2e/o6+UfWzbpSTuarBDLxH
bKdq7QuJc9RX8e7bRutv97NXiJpKHxFLP0eR1Y2h2czeNZLf/NK3t0xEo5GdwBAa
P1iS9WF1uKzRm0AtS3VXJ9DR6n0ocxscrzTwew3yaQqikniDyRZoMWuU1K9bC2mY
Bzv0RL7QdvRE9I0PZSuwTCijUKaUf2wdtXIUUeFNuqKnybQAwtqu9p2j+FWxqHcF
CHVYA9DSL5Ua894GhXrMNyByT6Z/55tS2sPiscl4FCjcwWtCn8kZqQoOINdDEXE4
rAsPKWp+MeLKe5i9C+qYBtK7LimsRbCsJw/l1t05MQE7S9IwZNIlPQNJNzEg1uG3
tyBKA6uC35szPxiJIGBzVx5PICLmkDE1K5jc5mAuMtrIzW2nPLrfhkaS5K4GFRDe
kC5ZW/OTkkJj/AsV2UOqZ+r6f6WKyZXKTWzqDRBNgqzu3jP8x5CXHURpTZ230QUV
wqCQFyD4jz79BzJSwjSkmg==
`pragma protect end_protected
endmodule